[package]
name = "etf"
version = "0.1.0"
authors = ["Serge Barral <serge@fi3k-barral.com>"]
edition = "2018"

[features]
# Use fused multiply-add.
# May be faster if supported by the target, but not necessarily.
fma = []

[dev-dependencies]
libm = "0.2"
rand_pcg = "0.2"
rand_xoshiro = "0.4"
rand_distr = "0.2"
criterion = "0.3"

[dependencies]
rand = "0.7"

[[bench]]
name = "benchmark"
harness = false

